SocialNetwork/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace SocialNetwork.Controllers
{
    public class LanguageController : Controller
    {
        [HttpPost]
        public IActionResult Change(string culture)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)));

            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

SocialNetwork/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NuGet.Packaging;
using NuGet.Protocol.Plugins;
using SocialNetwork.Data;
using SocialNetwork.Models;

namespace SocialNetwork.Controllers
{
    public class UsersController : Controller
    {
        private readonly SocialNetworkService _service;

        public UsersController(SocialNetworkService service)
        {
            _service = service;
        }

        // GET: Users
        public async Task<IActionResult> List()
        {
            if (IsCurentUserAdmin())
                return View(await _service.GetAllUsers());

            else return NotFound();
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            if (IsCurentUserAdmin())
                return View();

            else return NotFound();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Login,CreationDateTime")] User user)
        {
            if (IsCurentUserAdmin())
            {
                if (ModelState.IsValid)
                    _service.CreateUser(user);

                return View(user);
            }
            else return NotFound();
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string login)
        {
            if (IsCurentUserAdmin())
            {
                if (login == null)
                    return NotFound();

                var user = await _service.GetUserByLoginOrNull(login);
                if (user == null)
                    return NotFound();

                return View(user);
            }
            else return NotFound();
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string login)
        {
            if (IsCurentUserAdmin())
            {
                var userToDelete = await _service.GetUserByLoginOrNull(login);
                if (userToDelete != null)
                {
                    _service.RemoveUser(userToDelete);
                    if (userToDelete.Login == Request.Cookies["login"])
                        return Logout();
                }
                return RedirectToAction(nameof(List));
            }
            else return NotFound();
        }

        // POST: Users/Login
        [HttpPost]
        public IActionResult Login(string login)
        {
            if (!IsUserLoggedIn())
            {
                var user = _service.GetUserByLoginOrNull(login);
                if (user != null)
                {
                    Response.Cookies.Append("login", login);
                    return RedirectToAction("Index", "Friends");
                }
                return RedirectToAction("Index", "Home");
            }
            else return NotFound();
        }

        // POST: Users/Logout
        [HttpPost]
        public IActionResult Logout()
        {
            if (IsUserLoggedIn())
            {
                if (Request.Cookies["login"] != null)
                    Response.Cookies.Delete("login");
                return RedirectToAction("Index", "Home");
            }
            else return NotFound();
        }

        [HttpPost]
        public IActionResult Init()
        {
            var users = new List<User>{
                new User("John", DateTime.Now.AddDays(-1)),
                new User("Alice", DateTime.Now.AddDays(-2)),
                new User("Bob", DateTime.Now.AddDays(-3)),
            };


            
            users[0].AddFriend(users[1]);
            users[1].AddFriend(users[0]); users[1].AddFriend(users[2]);
            users[2].AddFriend(users[1]); users[2].AddFriend(users[3]);

            _service.CreateUsers(users);
            return RedirectToAction(nameof(List));
        }

        [HttpPost]
        public IActionResult Clear()
        {
            _service.RemoveAllExceptAdmin();
            return RedirectToAction(nameof(List));
        }

        private bool IsCurentUserAdmin()
        {
            if (Request.Cookies.TryGetValue("login", out string? login))
            {
                return login == "admin";
            }
            else return false;
        }

        private bool IsUserLoggedIn() => Request.Cookies.TryGetValue("login", out _);
    }
}

SocialNetwork/Views/Shared/_Layout.cshtml
@{
    Context.Request.Cookies.TryGetValue("login", out string? login);

    var requestCultureFeature = Context.Features.Get<IRequestCultureFeature>();
    var requestCulture = requestCultureFeature.RequestCulture;
    var cultureItems = LocOptions.Value.SupportedUICultures
    .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
    .ToList();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Social Network</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SocialNetwork.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <form asp-controller="Language" asp-action="Change">
                <select name="culture" asp-for="@requestCultureFeature.RequestCulture.UICulture" asp-items="@cultureItems" onchange="this.form.submit();">
                </select>
            </form>
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Social Network"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            if (login != null)
                            {
                                <li class="nav-item">

                                    <form asp-controller="Users" asp-action="Logout">
                                        <label>@Localizer["Hello"] <b>@login</b></label>
                                        <input type="submit" value="@Localizer["Logout"]" class="btn btn-danger" />
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <form asp-controller="Users" asp-action="Login">
                                        <input type="text" name="login" />
                                        <input type="submit" value="@Localizer["Login"]" class="btn btn-primary" />
                                    </form>
                                </li>
                            }
                            if (login != null && login == "admin")
                            {
                                if (login == "admin")
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="List">@Localizer["Users"]</a>
                                    </li>
                                }
                            }
                            if (login != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Friends" asp-action="Index">@Localizer["Friends"]</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - @Localizer["Social Network"] - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Privacy"]</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>